// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgvfwwrejgiumqsssgsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndmZ3d3JlamdpdW1xc3NzZ3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDcwMjIsImV4cCI6MjA2Mjc4MzAyMn0.XMqpcLpyAIMnaQcwsKi6t_Hd_wcSa6pR5_gwPfg2AOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);